version: '3.4'
networks:
  appnet:
    external:
      name: appnet

secrets:
  public.pem:
    external: true
  private.pem:
    external: true

services:
  app:
    image: threax/nginxproxy
    container_name: threax-nginxproxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - public.pem
      - private.pem
    ports:
      - "80:80"
      - "443:443"
    build:
      context:  .
      dockerfile: Dockerfile
    environment:
      - THREAX_NGINX_SHOW_CONFIG=true
      - THREAX_NGINX_SWARM_MODE=true
    # logging:
      # driver: fluentd