version: '3.4'
networks:
  appnet:
    external:
      name: appnet

secrets:
  public.pem:
    external: true
  private.pem:
    external: true

services:
  server:
    image: threax.proxy
    container_name: threaxproxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - public.pem
      - private.pem
    ports:
      - "80:80"
      - "443:443"
    build:
      context:  .
      dockerfile: Dockerfile
    # logging:
      # driver: fluentd